FROM quay.io/quarkus/ubi9-quarkus-mandrel-builder-image:jdk-21 AS builder
WORKDIR /build
COPY --chown=quarkus:quarkus . .
USER quarkus
RUN ./mvnw package -Dnative -DskipTests

FROM quay.io/quarkus/ubi9-quarkus-micro-image:2.0
WORKDIR /work/
COPY --chown=1001:root --chmod=0755 --from=builder /build/target/*-runner /work/application

EXPOSE 8080
USER 1001

ENTRYPOINT ["./application", "-Dquarkus.http.host=0.0.0.0"]
