quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=ash
quarkus.datasource.password=pikachu
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/pokedex

quarkus.smallrye-openapi.info-title=Pokemon API
quarkus.smallrye-openapi.info-version=1.0.0
quarkus.swagger-ui.always-include=true
quarkus.swagger-ui.path=/swagger-ui

quarkus.native.builder-image=quay.io/quarkus/ubi9-quarkus-mandrel-builder-image:jdk-21